version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: unified_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
      MYSQL_DATABASE: products
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d

volumes:
  mysql_data: