server:
  port: 80831

spring:
  application:
    name: stock-service
  datasource:
    url: jdbc:mysql://localhost:3306/asset
    username: appuser
    password: apppass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address=true

build:
  version: @project.version@

